<template>
  <div @paste="onPaste">
    <header class="bg-primary-pus text-white">
      <div class="container text-center">
        <h1 class="text-white">{{ $t('main.welcome', { title: 'PASTE YOUR SCREENS' }) }}</h1>
        <p class="lead">{{ $t('main.welcome_subtext') }}</p>
      </div>
    </header>

    <div class="home">
      <section id="services" class="bg-light">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 mx-auto">
              <p class="text-center">
                Focus this page and press <kbd>CTRL</kbd> + <kbd>V</kbd>. The image in your clipboard will be uploaded !
              </p>
              <p class="text-center" v-show="!user">
                <i>Register to set your screen privacy to private and get your own gallery.</i>
              </p>
              <div style="border:1px solid grey;"></div>
              <div id="postSetting" class="row" v-show="clipboardImage">
                <div class="col-md-4 form-group">
                  <input class="form-control input-md" placeholder="Title" required
                         id="screenTitle"
                         v-model="title"
                         type="text"
                         name="title" >
                </div>
                <div class="col-md-2 form-group">
                  <select id="screenPrivacy" class="input-md form-control">
                    <option value="false">Public</option>
                    <option v-if="user" value="true">Private</option>
                  </select>
                </div>
                <div class="form-group">
                  <button class="btn btn-md btn-success" @click="postUpload">Upload</button>
                </div>
              </div>
              <div id="imgPreview" class="text-center" :class="image.classList"></div>
            </div>
          </div>
        </div>
      </section>
    </div>
    <notifications
        position="bottom left"
        class="notif"
        width="350px"
        animation-type="css"
        :closeOnClick="true"
        :duration="5000"
        :max="1"
    />
  </div>
</template>

<style>
.notif {
   padding: 15px;
}
</style>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'
import axios from 'axios'
import $ from 'jquery'

interface Event {
  clipboardData : any;
}

@Component
export default class Home extends Vue {
  private title = ''
  private privacy: 'public' | 'private' = 'public'

  public clipboardImage = false
  public imagePreview: string[] = []
  public image: {
    base64: string
    size: number
    classList: string
  } = { base64: '', size: 0, classList: '' }
  public notif: {
    type: string,
  } = {
    type: 'danger'
  }
  data() {
    return {
      user: null,
      clipboard: null,
    }
  }

  onPaste(event : Event) : void {
    const { clipboardData } = event
    let items = clipboardData.items

    if (items[0].type.indexOf('image') == -1) {
      this.$notify({
        title: '⚠️ Wrong Content :',
        text: 'Your actual clipboard isn\'t a screenshot.',
        type: 'error',
      })
    } else {
      this.clipboardImage = true
      let blob = items[0].getAsFile()
      const fr = new FileReader()
      $('#imgPreview > img').remove()
      fr.readAsDataURL(blob)
      fr.onloadend = () => {
        const img = new Image()
        img.onload = () => $('#imgPreview').append(img)
        img.src = fr.result as string
        this.image.base64 = String(fr.result)
        this.image.size = blob.size
        this.image.classList = 'img-fluid center-block'
      }
    }
  }

  postUpload = () : void => {
    // todo add a uniq key generated by server to ensure that the method is call in legit way
    if (this.image.base64.length < 30) return
    const { title, privacy, image } = this
    axios.post('/screens/save', { title, privacy, image }).then((data: Record<string, any>) => {
      if (data.path) {
        const url = data.private === '1' ? 'https://pasteurscreens.tk' : 'https://purs.tk'
        $(location).attr('href', `${ url }/-${ data.shareKey }`)
      }
    }).catch(reason => {
      this.$notify({
        title: '⚠️ Unable to upload your screenshot :',
        text: reason,
        type: 'error',
      })
    })
  }
}
</script>