<template>
  <div @copy="pastScreenshot">
    <header class="bg-primary-pus text-white">
    <div class="container text-center">
      <h1 class="text-white">{{ $t('main.welcome', { title: 'PASTE YOUR SCREENS' }) }}</h1>
      <p class="lead">{{ $t('main.welcome_subtext') }}</p>
    </div>
    </header>

    <div class="home">
    <section id="services" class="bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 mx-auto">
            <p class="text-center">
              Focus this page and press <kbd>CTRL</kbd> + <kbd>V</kbd>. The image in your clipboard will be uploaded !
            </p>
            <div style="border:1px solid grey;"></div>
            <div id="postSetting" class="hidden">
              <div class="col-md-9 pull-left">
                <input id="screenTitle" type="text" placeholder="Title" class="input-md">
                <select id="screenPrivacy" class="input-md">
                  <option value="false">Public</option>
                  <option v-if="user" value="true">Private</option>
                </select>
              </div>
              <div class="col-md-3 pull-right">
                <button class="btn btn-md btn-success" onclick="return postUpload();">Upload</button>
              </div>
            </div>
            <div id="imgPreview" class="text-center"></div>
          </div>
        </div>
      </div>
    </section>
    <div id="base64" class="hidden"></div>
    <div>
        <p>{{ $tc('main.screenshots_uploaded', 42) }}</p>
        <p>{{ $d(new Date(), 'short') }}</p>
        <p>{{ $n(100, 'currency') }}</p>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'
import $ from 'jquery'

@Component
export default class Home extends Vue {

  pastScreenshot = (): void => {
    const imgPreview = $('#imgPreview')
    const postUpload = () => {
      // todo add a uniq key generated by server to ensure that the method is call in legit way
      const base64 = imgPreview.attr('data-base64')
      const size = imgPreview.attr('data-size')
      const title = $('#screenTitle').val()
      const _csrf = $('#_csrf').val()
      const privacy = $('#screenPrivacy option:selected').text() === 'Private' ? 1 : 0
      if (base64?.length || 0 < 30) return false
      $.post('/screens/save', { base64, size, title, privacy, _csrf }, (data) => {
        if (data.path) {
          const url = data.private === '1' ? 'https://pasteurscreens.tk' : 'https://purs.tk'
          $(location).attr('href', `${ url }/-${ data.shareKey }`)
        }
      })
    }

    $('body').on('paste', (e) => {
      $('#imgPreview > img').remove()
      // @ts-ignore
      const data = e.originalEvent.clipboardData.items[0].getAsFile()
      if (data instanceof File) {
        $('#postSetting').show()
        const fr = new FileReader()

        fr.readAsDataURL(data)
        fr.onloadend = () => {
          const img = new Image()
          img.onload = () => imgPreview.append(img)
          // @ts-ignore
          img.src = fr.result
          // @ts-ignore
          img.classList = 'img-fluid center-block'
          // @ts-ignore
          imgPreview.attr('data-size', data.size).attr('data-base64', fr.result)
        }
      } else {
        Vue.notify({
          title: '⚠️ Wrong Content :',
          text: 'Your actual clipboard isn\'t a screenshot.',
          type: 'danger',
          duration: 5000,
        })
      }
    })
  }
}
</script>